// frontend/src/components/protocol/ContractTable.tsx
//
// Three-row table displaying the deployed contract addresses for:
//   • ComplianceGate  — main entry point, verifies ZK proofs + nullifiers
//   • SanctionsList   — stores Merkle roots + root history
//   • Verifier        — UltraHonk on-chain verifier (generated by Noir)
//
// Each row shows:
//   • Contract name + role badge
//   • Full address (truncated) with copy action
//   • Etherscan link (opens in new tab)
//   • Live on-chain status check (bytecode length via eth_getCode)

import React, { useCallback, useEffect, useState } from "react";

import {
  COMPLIANCE_GATE_ADDRESS,
  SANCTIONS_LIST_ADDRESS,
  VERIFIER_ADDRESS,
  BLOCK_EXPLORER_URL,
  SUPPORTED_CHAIN_NAME,
  addrUrl,
} from "@/lib/constants";
import { formatHash } from "@/lib/format";
import { createDefaultPublicClient } from "@/lib/chain/contracts";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type ContractStatus = "idle" | "checking" | "deployed" | "undeployed" | "error";

interface ContractRow {
  id:       string;
  name:     string;
  role:     string;
  address:  string;
  /** Accent colour for role badge */
  color:    "teal" | "purple" | "amber";
}

// ---------------------------------------------------------------------------
// Static contract definitions
// ---------------------------------------------------------------------------

const CONTRACT_ROWS: ContractRow[] = [
  {
    id:      "compliance-gate",
    name:    "ComplianceGate",
    role:    "Proof Entry Point",
    address: COMPLIANCE_GATE_ADDRESS,
    color:   "teal",
  },
  {
    id:      "sanctions-list",
    name:    "SanctionsList",
    role:    "Merkle Root Registry",
    address: SANCTIONS_LIST_ADDRESS,
    color:   "purple",
  },
  {
    id:      "verifier",
    name:    "Verifier",
    role:    "UltraHonk Verifier",
    address: VERIFIER_ADDRESS,
    color:   "amber",
  },
];

// ---------------------------------------------------------------------------
// Colour token maps
// ---------------------------------------------------------------------------

const BADGE_STYLE: Record<ContractRow["color"], string> = {
  teal:   "border-teal-500/25   bg-teal-500/8   text-teal-400",
  purple: "border-purple-500/25 bg-purple-500/8 text-purple-400",
  amber:  "border-amber-500/25  bg-amber-500/8  text-amber-400",
};

const DOT_COLOR: Record<ContractRow["color"], string> = {
  teal:   "bg-teal-400",
  purple: "bg-purple-400",
  amber:  "bg-amber-400",
};

// ---------------------------------------------------------------------------
// Status indicator
// ---------------------------------------------------------------------------

function StatusDot({ status }: { status: ContractStatus }) {
  if (status === "idle" || status === "checking") {
    return (
      <span
        className="inline-flex h-2 w-2 animate-pulse rounded-full bg-zinc-700"
        aria-label="Checking…"
      />
    );
  }
  if (status === "deployed") {
    return (
      <span className="relative inline-flex h-2 w-2" aria-label="Deployed">
        <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-teal-400 opacity-50" />
        <span className="relative inline-flex h-2 w-2 rounded-full bg-teal-500" />
      </span>
    );
  }
  if (status === "undeployed") {
    return (
      <span
        className="inline-flex h-2 w-2 rounded-full bg-rose-500"
        aria-label="Not deployed"
      />
    );
  }
  // error
  return (
    <span
      className="inline-flex h-2 w-2 rounded-full bg-amber-500"
      aria-label="Check failed"
    />
  );
}

function statusLabel(s: ContractStatus): string {
  switch (s) {
    case "idle":
    case "checking":   return "Checking…";
    case "deployed":   return "Deployed";
    case "undeployed": return "Not deployed";
    case "error":      return "Check failed";
  }
}

function statusTextColor(s: ContractStatus): string {
  switch (s) {
    case "deployed":   return "text-teal-400";
    case "undeployed": return "text-rose-400";
    case "error":      return "text-amber-400";
    default:           return "text-zinc-600";
  }
}

// ---------------------------------------------------------------------------
// Copy button
// ---------------------------------------------------------------------------

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);

  async function handle(e: React.MouseEvent) {
    e.preventDefault();
    e.stopPropagation();
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch { /* silent */ }
  }

  return (
    <button
      onClick={handle}
      aria-label={copied ? "Copied" : "Copy address"}
      title={copied ? "Copied!" : "Copy full address"}
      className={[
        "rounded p-1 transition-colors duration-150",
        "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-500",
        copied
          ? "text-teal-400"
          : "text-zinc-700 hover:text-zinc-300 hover:bg-zinc-800",
      ].join(" ")}
    >
      {copied ? (
        /* Checkmark */
        <svg viewBox="0 0 12 12" className="h-3 w-3" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
          <path d="M2 6l2.5 2.5L10 3.5" />
        </svg>
      ) : (
        /* Copy icon */
        <svg viewBox="0 0 12 12" className="h-3 w-3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
          <rect x="3.5" y="3.5" width="6.5" height="7" rx="1" />
          <path d="M7.5 3.5V2.5a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v5.5a1 1 0 0 0 1 1H3" />
        </svg>
      )}
    </button>
  );
}

// ---------------------------------------------------------------------------
// Etherscan link button
// ---------------------------------------------------------------------------

function EtherscanLink({ address }: { address: string }) {
  if (!address) return null;
  return (
    <a
      href={addrUrl(address)}
      target="_blank"
      rel="noopener noreferrer"
      aria-label="View on Etherscan"
      title="View on Etherscan"
      className={[
        "rounded p-1 text-zinc-700 transition-colors duration-150",
        "hover:text-zinc-300 hover:bg-zinc-800",
        "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-500",
      ].join(" ")}
    >
      {/* External link icon */}
      <svg viewBox="0 0 12 12" className="h-3 w-3" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
        <path d="M5 2H2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V7" />
        <path d="M8 1h3v3M11 1 6 6" />
      </svg>
    </a>
  );
}

// ---------------------------------------------------------------------------
// Address cell — missing address guard
// ---------------------------------------------------------------------------

function AddressCell({ address }: { address: string }) {
  if (!address) {
    return (
      <span className="text-[11px] italic text-zinc-700">
        Not configured
      </span>
    );
  }

  return (
    <div className="flex items-center gap-1">
      <span className="font-mono text-[11px] text-zinc-400 tabular-nums">
        {formatHash(address, 10, 8)}
      </span>
      <CopyButton value={address} />
      <EtherscanLink address={address} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// On-chain status check
// ---------------------------------------------------------------------------

async function checkDeployment(address: string): Promise<ContractStatus> {
  if (!address || !address.startsWith("0x") || address.length !== 42) {
    return "undeployed";
  }
  try {
    const client = createDefaultPublicClient();
    const code   = await client.getBytecode({ address: address as `0x${string}` });
    // code is undefined or "0x" when no contract exists
    return code && code !== "0x" ? "deployed" : "undeployed";
  } catch {
    return "error";
  }
}

// ---------------------------------------------------------------------------
// ContractTable
// ---------------------------------------------------------------------------

export interface ContractTableProps {
  className?: string;
}

export function ContractTable({ className = "" }: ContractTableProps) {
  const [statuses, setStatuses] = useState<Record<string, ContractStatus>>(
    () => Object.fromEntries(CONTRACT_ROWS.map((r) => [r.id, "idle"])),
  );

  const [lastChecked, setLastChecked] = useState<number | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // ── Check all deployments ────────────────────────────────────────────────
  const checkAll = useCallback(async () => {
    setIsRefreshing(true);
    // Set all to "checking"
    setStatuses(
      Object.fromEntries(CONTRACT_ROWS.map((r) => [r.id, "checking"])),
    );

    await Promise.all(
      CONTRACT_ROWS.map(async (row) => {
        const status = await checkDeployment(row.address);
        setStatuses((prev) => ({ ...prev, [row.id]: status }));
      }),
    );

    setLastChecked(Date.now());
    setIsRefreshing(false);
  }, []);

  // Run once on mount
  useEffect(() => {
    checkAll();
  }, [checkAll]);

  // ── Derived: all deployed? ───────────────────────────────────────────────
  const allDeployed = CONTRACT_ROWS.every(
    (r) => statuses[r.id] === "deployed",
  );

  const anyError = CONTRACT_ROWS.some(
    (r) =>
      statuses[r.id] === "undeployed" || statuses[r.id] === "error",
  );

  // ── Last checked label ───────────────────────────────────────────────────
  const lastCheckedLabel = lastChecked
    ? new Date(lastChecked).toLocaleTimeString("en-US", {
        hour:   "numeric",
        minute: "2-digit",
        second: "2-digit",
      })
    : null;

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <div
      className={[
        "overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950",
        className,
      ].join(" ")}
    >
      {/* ── Header ────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between gap-3 border-b border-zinc-800 px-5 py-3">
        <div className="flex items-center gap-2">
          {/* Contract icon */}
          <svg
            viewBox="0 0 18 18"
            className="h-4 w-4 text-zinc-400"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <rect x="2" y="2" width="14" height="14" rx="2" />
            <path d="M5 6h8M5 9h5M5 12h3" />
          </svg>
          <span className="text-xs font-semibold tracking-wide text-zinc-300">
            Deployed Contracts
          </span>
        </div>

        <div className="flex items-center gap-2">
          {/* Network badge */}
          <span className="rounded-full border border-zinc-800 bg-zinc-900 px-2 py-0.5 text-[10px] font-medium text-zinc-500">
            {SUPPORTED_CHAIN_NAME}
          </span>

          {/* Overall health badge */}
          {allDeployed && (
            <span className="rounded-full border border-teal-500/25 bg-teal-500/8 px-2 py-0.5 text-[10px] font-semibold text-teal-400">
              All Live
            </span>
          )}
          {anyError && (
            <span className="rounded-full border border-rose-500/25 bg-rose-500/8 px-2 py-0.5 text-[10px] font-semibold text-rose-400">
              Check Failed
            </span>
          )}

          {/* Refresh button */}
          <button
            onClick={checkAll}
            disabled={isRefreshing}
            aria-label="Refresh contract status"
            title="Re-check deployment status"
            className={[
              "rounded-lg border border-zinc-800 bg-zinc-900 p-1.5",
              "text-zinc-500 transition-colors duration-150",
              "hover:border-zinc-700 hover:text-zinc-300",
              "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-500",
              "disabled:cursor-not-allowed disabled:opacity-40",
            ].join(" ")}
          >
            <svg
              viewBox="0 0 12 12"
              className={`h-3 w-3 ${isRefreshing ? "animate-spin" : ""}`}
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
            >
              <path d="M10.5 6A4.5 4.5 0 1 1 7 1.6" />
              <polyline points="7,1 10.5,1 10.5,4.5" />
            </svg>
          </button>
        </div>
      </div>

      {/* ── Table ─────────────────────────────────────────────────────── */}
      <div className="overflow-x-auto">
        <table className="w-full" aria-label="Deployed contract addresses">
          <thead>
            <tr className="border-b border-zinc-800/80">
              {[
                { label: "Contract",  title: "Contract name and role"        },
                { label: "Address",   title: "Deployed address on-chain"     },
                { label: "Status",    title: "Live deployment check"         },
              ].map(({ label, title }) => (
                <th
                  key={label}
                  scope="col"
                  title={title}
                  className="px-3 py-2 text-left first:pl-5 last:pr-5"
                >
                  <span className="cursor-help text-[10px] font-medium uppercase tracking-widest text-zinc-600">
                    {label}
                  </span>
                </th>
              ))}
            </tr>
          </thead>

          <tbody>
            {CONTRACT_ROWS.map((row) => {
              const status = statuses[row.id] ?? "idle";
              return (
                <tr
                  key={row.id}
                  className="group border-b border-zinc-800/50 last:border-0 transition-colors duration-100 hover:bg-zinc-900/40"
                >
                  {/* Contract name + role badge */}
                  <td className="py-4 pl-5 pr-3 align-middle">
                    <div className="flex flex-col gap-1.5">
                      <div className="flex items-center gap-2">
                        <span
                          className={[
                            "h-1.5 w-1.5 shrink-0 rounded-full",
                            DOT_COLOR[row.color],
                          ].join(" ")}
                          aria-hidden="true"
                        />
                        <span className="text-xs font-semibold text-zinc-200">
                          {row.name}
                        </span>
                      </div>
                      <span
                        className={[
                          "ml-3.5 inline-flex w-fit items-center rounded-full border px-1.5 py-0.5",
                          "text-[9px] font-semibold uppercase tracking-wider",
                          BADGE_STYLE[row.color],
                        ].join(" ")}
                      >
                        {row.role}
                      </span>
                    </div>
                  </td>

                  {/* Address */}
                  <td className="py-4 px-3 align-middle">
                    <AddressCell address={row.address} />
                  </td>

                  {/* Status */}
                  <td className="py-4 pl-3 pr-5 align-middle">
                    <div className="flex items-center gap-2">
                      <StatusDot status={status} />
                      <span
                        className={[
                          "text-[11px] font-medium",
                          statusTextColor(status),
                        ].join(" ")}
                      >
                        {statusLabel(status)}
                      </span>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Footer ────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between gap-3 border-t border-zinc-800/50 px-5 py-2.5">
        <p className="text-[10px] text-zinc-700">
          Status verified via{" "}
          <code className="rounded bg-zinc-900 px-1 py-0.5 font-mono text-[9px] text-zinc-500">
            eth_getCode
          </code>{" "}
          — non-empty bytecode = deployed
        </p>
        {lastCheckedLabel && (
          <p className="shrink-0 text-[10px] tabular-nums text-zinc-700">
            Checked {lastCheckedLabel}
          </p>
        )}
      </div>
    </div>
  );
}

export default ContractTable;