packages:
  - frontend
  - oracle

overrides:
  typescript: ^5.5.0

allowBuilds:
  '@reown/appkit': true
  bufferutil: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  unrs-resolver: true
  utf-8-validate: true
