// AUTO-GENERATED by scripts/sync-abis.sh — do not edit manually
// Last synced: 2026-06-07T13:17:14Z

export { default as complianceGateAbi } from './ComplianceGate.json';
export { default as honkVerifierAbi } from './HonkVerifier.json';
export { default as sanctionsListAbi } from './SanctionsList.json';

// Re-export all ABI filenames as a const tuple for tooling
export const ABI_CONTRACT_NAMES = [
  'ComplianceGate',
  'HonkVerifier',
  'SanctionsList',
] as const;

export type AbiContractName = (typeof ABI_CONTRACT_NAMES)[number];
