[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

solc_version = "0.8.33"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

ffi = false
fs_permissions = [{ access = "read", path = "./out" }]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x3e8f2a"

[profile.default.invariant]
runs = 64
depth = 15
fail_on_revert = true

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
fuzz = { runs = 1000 }
verbosity = 3

[profile.deploy]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "mainnet" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
override_spacing = true
wrap_comments = true
ignore = ["src/interfaces/"]

[doc]
out = "docs"
repository = "https://github.com/vamshiganesh/NullProof.git"