// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {IComplianceGate} from "./interfaces/IComplianceGate.sol";
import {ISanctionsList} from "./interfaces/ISanctionsList.sol";
import {IVerifier} from "./interfaces/IVerifier.sol";

/// @title ComplianceGate
/// @notice Main integration contract for ZK-gated OFAC compliance enforcement.
/// @dev DeFi protocols call assertCompliant() inside their deposit() or swap()
///      function. The call reverts if the submitted ZK proof is invalid, expired,
///      or if the nullifier has already been consumed. On success the nullifier
///      is stored permanently to prevent proof replay across transactions.
///
///      Proof lifecycle:
///        1. User generates proof in browser via noir_js + bb.js (~24s)
///        2. Frontend calls checkCompliant() (view) to confirm validity pre-tx
///        3. Protocol contract calls assertCompliant() inside deposit()
///        4. ComplianceGate calls IVerifier.verify() on-chain
///        5. ComplianceGate calls ISanctionsList.isKnownRoot() to validate root
///        6. Nullifier is stored — proof cannot be reused
///        7. Deposit proceeds
contract ComplianceGate is IComplianceGate, Ownable, ReentrancyGuard {
    // -------------------------------------------------------------------------
    // Constants
    // -------------------------------------------------------------------------

    /// @dev Default proof validity window: 24 hours in seconds.
    uint256 public constant DEFAULT_VALIDITY_WINDOW = 86_400;

    /// @dev Maximum validity window: 7 days. Prevents owner from setting
    ///      an absurdly long window that negates the compliance guarantees.
    uint256 public constant MAX_VALIDITY_WINDOW = 7 * 86_400;

    /// @dev Minimum validity window: 1 hour. Prevents owner from making
    ///      proofs expire so fast they become unusable.
    uint256 public constant MIN_VALIDITY_WINDOW = 3_600;

    // -------------------------------------------------------------------------
    // Storage
    // -------------------------------------------------------------------------

    /// @dev Address of the ISanctionsList contract.
    ISanctionsList private _sanctionsList;

    /// @dev Address of the IVerifier contract (auto-generated by nargo/bb).
    IVerifier private _verifier;

    /// @dev Proof validity window in seconds. Default 86400 (24h).
    uint256 private _validityWindow;

    /// @dev Whether proof submission is currently paused.
    bool private _submissionPaused;

    /// @dev Maps nullifier => true if already consumed.
    mapping(bytes32 => bool) private _usedNullifiers;

    /// @dev Maps nullifier => timestamp when it was consumed.
    mapping(bytes32 => uint256) private _nullifierUsedAt;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /// @param initialOwner     Address that receives Ownable ownership.
    /// @param sanctionsListAddr Address of the deployed SanctionsList contract.
    /// @param verifierAddr      Address of the deployed Verifier contract.
    constructor(
        address initialOwner,
        address sanctionsListAddr,
        address verifierAddr
    ) Ownable(initialOwner) {
        require(sanctionsListAddr != address(0), "ComplianceGate: zero sanctions list");
        require(verifierAddr != address(0), "ComplianceGate: zero verifier");

        _sanctionsList = ISanctionsList(sanctionsListAddr);
        _verifier = IVerifier(verifierAddr);
        _validityWindow = DEFAULT_VALIDITY_WINDOW;
    }

    // -------------------------------------------------------------------------
    // Core compliance check
    // -------------------------------------------------------------------------

    /// @inheritdoc IComplianceGate
    function assertCompliant(
        bytes calldata proof,
        bytes32[] calldata publicInputs,
        bytes32 nullifier
    ) external override nonReentrant {
        if (_submissionPaused) revert SubmissionPaused();
        if (proof.length == 0) revert EmptyProof();
        if (_usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);

        bytes32 proofRoot = _extractRoot(publicInputs);

        if (!_sanctionsList.isKnownRoot(proofRoot)) revert UnknownRoot();
        if (_isRootExpired(proofRoot)) revert ProofExpired();
        if (!_verifier.verify(proof, publicInputs)) revert InvalidProof();

        _usedNullifiers[nullifier] = true;
        _nullifierUsedAt[nullifier] = block.timestamp;

        uint256 validUntil = _nullifierUsedAt[nullifier] + _validityWindow;

        emit ProofVerified(nullifier, proofRoot, validUntil);
        emit NullifierConsumed(nullifier, msg.sender);
    }

    /// @inheritdoc IComplianceGate
    function checkCompliant(
        bytes calldata proof,
        bytes32[] calldata publicInputs,
        bytes32 nullifier
    ) external view override returns (bool valid) {
        if (_submissionPaused) return false;
        if (proof.length == 0) return false;
        if (_usedNullifiers[nullifier]) return false;

        bytes32 proofRoot = _extractRoot(publicInputs);

        if (!_sanctionsList.isKnownRoot(proofRoot)) return false;
        if (_isRootExpired(proofRoot)) return false;

        return _verifier.verify(proof, publicInputs);
    }

    // -------------------------------------------------------------------------
    // Nullifier state
    // -------------------------------------------------------------------------

    /// @inheritdoc IComplianceGate
    function isNullifierUsed(bytes32 nullifier) external view override returns (bool) {
        return _usedNullifiers[nullifier];
    }

    /// @inheritdoc IComplianceGate
    function nullifierUsedAt(bytes32 nullifier) external view override returns (uint256) {
        return _nullifierUsedAt[nullifier];
    }

    // -------------------------------------------------------------------------
    // Configuration views
    // -------------------------------------------------------------------------

    /// @inheritdoc IComplianceGate
    function sanctionsList() external view override returns (address) {
        return address(_sanctionsList);
    }

    /// @inheritdoc IComplianceGate
    function verifier() external view override returns (address) {
        return address(_verifier);
    }

    /// @inheritdoc IComplianceGate
    function validityWindow() external view override returns (uint256) {
        return _validityWindow;
    }

    /// @inheritdoc IComplianceGate
    function submissionPaused() external view override returns (bool) {
        return _submissionPaused;
    }

    // -------------------------------------------------------------------------
    // Owner configuration
    // -------------------------------------------------------------------------

    /// @notice Update the proof validity window.
    /// @param newWindow New window in seconds. Must be between MIN and MAX.
    function setValidityWindow(uint256 newWindow) external onlyOwner {
        require(newWindow >= MIN_VALIDITY_WINDOW, "ComplianceGate: window too short");
        require(newWindow <= MAX_VALIDITY_WINDOW, "ComplianceGate: window too long");
        uint256 previous = _validityWindow;
        _validityWindow = newWindow;
        emit ValidityWindowUpdated(previous, newWindow);
    }

    /// @notice Point ComplianceGate at a new Verifier contract.
    /// @dev Called after regenerating the verifier from an updated circuit.
    function setVerifier(address newVerifier) external onlyOwner {
        require(newVerifier != address(0), "ComplianceGate: zero verifier");
        address previous = address(_verifier);
        _verifier = IVerifier(newVerifier);
        emit VerifierUpdated(previous, newVerifier);
    }

    /// @notice Pause or unpause proof submission.
    /// @dev Emergency circuit breaker. Does not affect view functions.
    function setSubmissionPaused(bool paused) external onlyOwner {
        _submissionPaused = paused;
        emit SubmissionPauseToggled(paused);
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /// @dev Extract the Merkle root from the public inputs array.
    ///      Index 0 is always the sanctions list root for NullProof circuits.
    function _extractRoot(bytes32[] calldata publicInputs) internal pure returns (bytes32) {
        require(publicInputs.length >= 1, "ComplianceGate: missing public inputs");
        return publicInputs[0];
    }

    /// @dev Returns true if the given root is older than the validity window.
    ///      A root is considered expired if it was published more than
    ///      _validityWindow seconds ago AND it is no longer the current root.
    function _isRootExpired(bytes32 root) internal view returns (bool) {
        if (root == _sanctionsList.currentRoot()) return false;

        (, uint256 rootTimestamp, bool exists) = _sanctionsList.getRootHistory(root);
        if (!exists) return true;

        return block.timestamp > rootTimestamp + _validityWindow;
    }
}